/**********************************************************************************************************************
 * \file cy_mipi_sensor.c
 * \copyright Copyright (C) Infineon Technologies AG 2025
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*******************************************************************************
* Header Files
*******************************************************************************/
#include <stdint.h>
#include "cy_device_headers.h"
#include "cy_gpio.h"
#include "cy_mipi_sensor.h"
#include "cy_pdl.h"
#include "cy_gfx_env.h"
#include "cybsp.h"
#include "mtb_hal.h"

/*******************************************************************************
* Global Variables
*******************************************************************************/
/* I2C port configuration macro */
static cy_stc_gpio_pin_config_t mipi_i2c_port_pin_cfg =
{
    .outVal   = 0x00,
    .intEdge  = 0,
    .intMask  = 0,
    .vtrip    = 0,
    .slewRate = 0,
    .driveSel = 0,
    .vregEn   = 0,
    .ibufMode = 0,
    .vtripSel = 0,
    .vrefSel  = 0,
    .vohSel   = 0,
};

/* I2C irq configuration macro */
static cy_stc_sysint_t mipi_i2c_irq_cfg =
{   .intrSrc = ((NvicMux4_IRQn << CY_SYSINT_INTRSRC_MUXIRQ_SHIFT) | CY_MIPI_CSI_I2C_IRQN),
    .intrPriority = 4
};

/* I2C master configuration macro */
static cy_stc_scb_i2c_config_t mipi_i2c_stc_config =
{
    .i2cMode             = CY_SCB_I2C_MASTER,
    .useRxFifo           = true,
    .useTxFifo           = true,
    .acceptAddrInFifo    = false,
    .ackGeneralAddr      = false,
    .enableWakeFromSleep = false
};

/* I2C master configuration structure */
static cy_stc_scb_i2c_master_xfer_config_t mipi_i2c_stc_master_config =
{
    .buffer       = 0,
    .bufferSize   = 0,
    .xferPending  = false
};


/* Flag to check validity of sensor during initialization */
static bool glIsValidSensor = false;

/* Sensor interface I2C contex */
static cy_stc_scb_i2c_context_t mipi_i2c_stc_context;
/*******************************************************************************
* Function Prototypes
*******************************************************************************/
/* Image Sensor local function definition */
static void Cy_OV5640_ImageSensor_Scb_I2C_IntrISR(void);
static void Cy_OV5640_ImageSensor_SetPeripheFracDiv24_5(uint64_t targetFreq, uint64_t sourceFreq, uint8_t divNum);
static void Cy_OV5640_ImageSensor_I2C_Master_Event(uint32_t locEvents);
static void Cy_OV5640_ImageSensor_I2C_Init(void);
static void Cy_OV5640_ImageSensor_PowerEnable(void);

static cy_en_mipi_sensor_result_t Cy_OV5640_ImageSensor_Set_Base(void);
static cy_en_mipi_sensor_result_t Cy_OV5640_ImageSensor_VerifyChipId(void);
static cy_en_mipi_sensor_result_t Cy_OV5640_ImageSensor_Read(uint16_t regAddr, uint8_t count, uint8_t *buf);
static cy_en_mipi_sensor_result_t Cy_OV5640_ImageSensor_Write(uint16_t regAddr, uint16_t count, uint8_t *buf);
static cy_en_mipi_sensor_result_t Cy_OV5640_ImageSensor_Write_ConfigurationSettings(cy_stc_Ov5640_reg_t * configSettings, uint16_t configSettingsSize);

static cy_en_mipi_sensor_result_t Cy_OV5640_ImageSensor_Set_VGA_Config(void);
static cy_en_mipi_sensor_result_t Cy_OV5640_ImageSensor_Set_720P_Config(cy_mipisensor_stc_cfg_t * pstcCfg);
static cy_en_mipi_sensor_result_t Cy_OV5640_ImageSensor_Set_1080P_Config(cy_mipisensor_stc_cfg_t * pstcCfg);
static cy_en_mipi_sensor_result_t Cy_OV5640_ImageSensor_Configure_Autofocus(void);

/*******************************************************************************
* Function Name: Cy_OV5640_ImageSensor_Scb_I2C_IntrISR
****************************************************************************//**
*
* \brief
* Sensor i2c interrupt callback.
*
* \param  none
*
* \return none
*
*******************************************************************************/
static void Cy_OV5640_ImageSensor_Scb_I2C_IntrISR(void)
{
    /* I2C interrupt handler for High-Level APIs */
    Cy_SCB_I2C_Interrupt(CY_MIPI_CSI_I2C_TYPE, &mipi_i2c_stc_context);
}

/*******************************************************************************
* Function Name: Cy_OV5640_ImageSensor_SetPeripheFracDiv24_5
****************************************************************************//**
*
* \brief
* Sensor i2c set up clock fractional divider.
*
* \param
* targetFreq : frequency for i2c operation
*
* \param
* sourceFreq : frequency for scb block
* 
* \param
* divNum : divider no used for the target frequency
*
* \return none
*
*******************************************************************************/
static void Cy_OV5640_ImageSensor_SetPeripheFracDiv24_5(uint64_t targetFreq, uint64_t sourceFreq, uint8_t divNum)
{
    uint64_t temp = ((uint64_t)sourceFreq << 5ull);
    uint32_t divSetting;

    divSetting = (uint32_t)(temp / targetFreq);
    Cy_SysClk_PeriphSetFracDivider(CY_SYSCLK_DIV_24_5_BIT, divNum, 
                                   (((divSetting >> 5u) & 0x00000FFF) - 1u), 
                                   (divSetting & 0x0000001F));
}

/*******************************************************************************
* Function Name: Cy_OV5640_ImageSensor_I2C_Master_Event
****************************************************************************//**
*
* \brief
* Sensor i2c event callback.
*
* \param
* locEvents : i2c block generated event id
*
* \return none
*
*******************************************************************************/
static void Cy_OV5640_ImageSensor_I2C_Master_Event(uint32_t locEvents)
{
    switch (locEvents)
    {
    case CY_SCB_I2C_MASTER_WR_IN_FIFO_EVENT:
        break;
    case CY_SCB_I2C_MASTER_WR_CMPLT_EVENT:
        break;
    case CY_SCB_I2C_MASTER_RD_CMPLT_EVENT:
        break;
    case CY_SCB_I2C_MASTER_ERR_EVENT:
        break;
    default:
        break;
    }
}

/*******************************************************************************
* Function Name: Cy_OV5640_ImageSensor_I2C_Init
****************************************************************************//**
*
* \brief
* Function to initialize i2c control path for image sensor
*
* \param  none
*
* \return none
*
* \note
* 
* 
*******************************************************************************/
static void Cy_OV5640_ImageSensor_I2C_Init(void)
{
   /*---------------------*/
    /* Clock Configuration */
    /*---------------------*/
/*    Cy_SysClk_HfClkEnable(CY_SYSCLK_HFCLK_2);*/
    Cy_SysClk_ClkHfEnable(CY_CFG_SYSCLK_CLKHF2);

    Cy_SysClk_PeriphAssignDivider(CY_MIPI_CSI_I2C_PCLK, CY_SYSCLK_DIV_24_5_BIT, CY_MIPI_I2C_DIVIDER_NO);
    Cy_OV5640_ImageSensor_SetPeripheFracDiv24_5(CY_MIPI_I2C_INCLK_TARGET_FREQ, CY_MIPI_I2C_SOURCE_CLK_FREQ, CY_MIPI_I2C_DIVIDER_NO);
    Cy_SysClk_PeriphEnableDivider(/*Cy_SysClk_GetClockGroup(CY_MIPI_CSI_I2C_PCLK),*/ CY_SYSCLK_DIV_24_5_BIT, CY_MIPI_I2C_DIVIDER_NO);

    /*--------------------*/
    /* Port Configuration */
    /*--------------------*/
    mipi_i2c_port_pin_cfg.driveMode = CY_GPIO_DM_OD_DRIVESLOW;
    mipi_i2c_port_pin_cfg.hsiom     = CY_MIPI_CSI_I2C_SDA_PIN_MUX;
    Cy_GPIO_Pin_Init(CY_MIPI_CSI_I2C_SDA_PORT, CY_MIPI_CSI_I2C_SDA_PIN, &mipi_i2c_port_pin_cfg);

    mipi_i2c_port_pin_cfg.driveMode = CY_GPIO_DM_OD_DRIVESLOW;
    mipi_i2c_port_pin_cfg.hsiom     = CY_MIPI_CSI_I2C_SCL_PIN_MUX;
    Cy_GPIO_Pin_Init(CY_MIPI_CSI_I2C_SCL_PORT, CY_MIPI_CSI_I2C_SCL_PIN, &mipi_i2c_port_pin_cfg);

    /*--------------------------*/
    /* Interrrupt Configuration */
    /*--------------------------*/
    Cy_SysInt_Init(&mipi_i2c_irq_cfg, (cy_israddress)Cy_OV5640_ImageSensor_Scb_I2C_IntrISR);
    NVIC_ClearPendingIRQ((IRQn_Type) mipi_i2c_irq_cfg.intrSrc);
    NVIC_EnableIRQ((IRQn_Type) NvicMux4_IRQn);
    /*--------------------------*/
    /*  Initilize & Enable I2C  */
    /*--------------------------*/
    Cy_SCB_I2C_Init(CY_MIPI_CSI_I2C_TYPE, &mipi_i2c_stc_config, &mipi_i2c_stc_context);
    Cy_SCB_I2C_SetDataRate(CY_MIPI_CSI_I2C_TYPE, CY_MIPI_I2C_DATARATE, CY_MIPI_I2C_INCLK_TARGET_FREQ);
    Cy_SCB_I2C_RegisterEventCallback(CY_MIPI_CSI_I2C_TYPE, (cy_cb_scb_i2c_handle_events_t)Cy_OV5640_ImageSensor_I2C_Master_Event, &mipi_i2c_stc_context);

    Cy_SCB_I2C_Enable(CY_MIPI_CSI_I2C_TYPE);    
}

/*******************************************************************************
* Function Name: Cy_OV5640_ImageSensor_PowerEnable
****************************************************************************//**
*
* \brief
* Function to enable power of image sensor.
*
* \param  none
*
* \return none
*
* \note
* PE and LE pins are used for the MIPI sensor control path.
* 
*******************************************************************************/
static void Cy_OV5640_ImageSensor_PowerEnable(void)
{
    cy_stc_gpio_pin_config_t mipi_sensor_pin_cfg = 
    {                                                  
        .outVal = 0x01,
        .driveMode = CY_GPIO_DM_STRONG_IN_OFF,
        .hsiom = CY_MIPI_CSI_IO_PE_PIN_MUX,
    };

    /* Initialize and enable port control pins */
    Cy_GPIO_Pin_Init(CY_MIPI_CSI_IO_PE_PORT, CY_MIPI_CSI_IO_PE_PIN, &mipi_sensor_pin_cfg);

    /* To boot the sensor correctly */
    DELAY(CY_OV5640_RESET_BOOT_DELAY);
    
    mipi_sensor_pin_cfg.hsiom = CY_MIPI_CSI_IO_LE_PIN_MUX;
    Cy_GPIO_Pin_Init(CY_MIPI_CSI_IO_LE_PORT, CY_MIPI_CSI_IO_LE_PIN, &mipi_sensor_pin_cfg);

    /* To boot the sensor correctly */
    DELAY(CY_OV5640_RESET_BOOT_DELAY);
}

/*******************************************************************************
* Function Name: Cy_OV5640_ImageSensor_Read
****************************************************************************//**
*
* \brief
* Function to read register in image sensor.
*
* \param
* regAddr : register address of image sensor
*
* \param
* count : no of bytes of data for read/write
*
* \param
* buf : pointer to the data buffer
*
* \return
* cy_en_mipi_sensor_result_t : function result type
*
*******************************************************************************/
static cy_en_mipi_sensor_result_t Cy_OV5640_ImageSensor_Read(uint16_t regAddr, uint8_t count, uint8_t *buf)
{
    cy_en_mipi_sensor_result_t status = CY_MIPI_SENSOR_SUCCESS;
    uint16_t cnt=0;
    
    CY_OV5640_SWAP_U16(regAddr);
    uint8_t *regadd = (uint8_t*)&regAddr;
    
    /* retry command */
    for(cnt=0; cnt<CY_OV5640_CMD_RETRY_COUNT ; cnt++)
    {
        mipi_i2c_stc_master_config.slaveAddress = CY_OV5640_I2C_ADRESS;
        mipi_i2c_stc_master_config.buffer = regadd;
        mipi_i2c_stc_master_config.bufferSize = 2;
        status = (cy_en_mipi_sensor_result_t)Cy_SCB_I2C_MasterWrite(CY_MIPI_CSI_I2C_TYPE, &mipi_i2c_stc_master_config, &mipi_i2c_stc_context);
        DELAY(CY_OV5640_CMD_IN_BW_DELAY);
        
        mipi_i2c_stc_master_config.buffer = buf;
        mipi_i2c_stc_master_config.bufferSize = count;
        status = (cy_en_mipi_sensor_result_t) Cy_SCB_I2C_MasterRead(CY_MIPI_CSI_I2C_TYPE, &mipi_i2c_stc_master_config, &mipi_i2c_stc_context);
        DELAY(CY_OV5640_CMD_IN_BW_DELAY);
        
        if (status == CY_MIPI_SENSOR_SUCCESS)
        {
            break;
        }
    }
    return status;
}

/*******************************************************************************
* Function Name: Cy_OV5640_ImageSensor_Write
****************************************************************************//**
*
* \brief
* Function to write register in image sensor.
*
* \param
* regAddr : register address of image sensor
* 
* \param
* count : no of bytes of data for read/write
*
* \param
* buf : pointer to the data buffer
*
* \return
* cy_en_mipi_sensor_result_t : function result type
*
*******************************************************************************/
static cy_en_mipi_sensor_result_t Cy_OV5640_ImageSensor_Write(uint16_t regAddr, uint16_t count, uint8_t *buf)
{
    cy_en_mipi_sensor_result_t status = CY_MIPI_SENSOR_SUCCESS;
    uint16_t cnt=0;
    static uint8_t dataWrite[CY_MIPI_I2C_WRITE_BUF_MAX+2];

    CY_ASSERT(count <= CY_MIPI_I2C_WRITE_BUF_MAX);

    dataWrite[0] = regAddr>>8;
    dataWrite[1] = regAddr & 0xFF;
    for(uint32_t i = 0; i<count; i++)
    {
        dataWrite[i+2] = buf[i];
    }
    
    /* retry command */
    for(cnt=0; cnt<CY_OV5640_CMD_RETRY_COUNT ; cnt++)
    {
        mipi_i2c_stc_master_config.slaveAddress = CY_OV5640_I2C_ADRESS;
        mipi_i2c_stc_master_config.buffer = dataWrite;
        mipi_i2c_stc_master_config.bufferSize = count + 2;              // two byte register size
        status = (cy_en_mipi_sensor_result_t)Cy_SCB_I2C_MasterWrite(CY_MIPI_CSI_I2C_TYPE, &mipi_i2c_stc_master_config, &mipi_i2c_stc_context);
        DELAY(CY_OV5640_CMD_IN_BW_DELAY);
        
        if (status == CY_MIPI_SENSOR_SUCCESS)
        {
            /* Fix for the reset to boot-up time */
            if(regAddr == CY_OV5640_SYSTEM_CTRL0)
            {
                DELAY(CY_OV5640_RESET_BOOT_DELAY);
            }
            break;
        }
    }
    return status;
}

/*******************************************************************************
* Function Name: Cy_OV5640_ImageSensor_Write_ConfigurationSettings
****************************************************************************//**
*
* \brief
* Function to write image sensor default configuration.
*
* \param
* cy_stc_Ov5640_reg_t : set of register needs to be configured
*
* \param
* configSettingsSize : size of the register array
*
* \return 
* cy_en_mipi_sensor_result_t : function result type
*
*******************************************************************************/
static cy_en_mipi_sensor_result_t Cy_OV5640_ImageSensor_Write_ConfigurationSettings(cy_stc_Ov5640_reg_t * configSettings, uint16_t configSettingsSize)
{
    uint16_t regCounter = 0;
    cy_en_mipi_sensor_result_t status = CY_MIPI_SENSOR_SUCCESS;
    uint8_t rwBuffer;

    for (regCounter = 0; ((regCounter < configSettingsSize) && (status == CY_MIPI_SENSOR_SUCCESS)); regCounter++)
    {
        rwBuffer = configSettings[regCounter].regValue;
        status = Cy_OV5640_ImageSensor_Write(configSettings[regCounter].regAddr, 1, &rwBuffer); 
    }

    return status;
}

/*******************************************************************************
* Function Name: Cy_OV5640_ImageSensor_VerifyChipId
****************************************************************************//**
*
* \brief
* Function to verify that the image sensor is the OV5640 chip.
*
* \param  none
*
* \return
* cy_en_mipi_sensor_result_t : function result type
*
* \note 
* Sets a global variable glIsValidSensor for further communication, needs
* to be called just after init();
*
*******************************************************************************/
static cy_en_mipi_sensor_result_t Cy_OV5640_ImageSensor_VerifyChipId(void)
{
    uint8_t readBuffer[2] = {0};
    cy_en_mipi_sensor_result_t status = CY_MIPI_SENSOR_SUCCESS;

    status = Cy_OV5640_ImageSensor_Read(CY_OV5640_CHIP_ID_HIGH_BYTE, 2, readBuffer);
    
    if (status != CY_MIPI_SENSOR_SUCCESS)
    {
        return status;
    }

    if (CY_OV5640_CHIP_ID != CY_OV5640_MAKEWORD(readBuffer[0],readBuffer[1]))
    {
        status = CY_MIPI_SENSOR_BAD_PARAM;
    }
    else
    {
        glIsValidSensor = true;
    }
    return status;
}

/*******************************************************************************
* Function Name: Cy_OV5640_ImageSensor_Set_Base
****************************************************************************//**
*
* \brief
* Configure defaults base setup for sensor.
*
* \param  none
*
* \return
* cy_en_mipi_sensor_result_t : function result type
*
*******************************************************************************/
static cy_en_mipi_sensor_result_t Cy_OV5640_ImageSensor_Set_Base(void)
{
    uint16_t configSize;
    if (glIsValidSensor != true)
    {
        return CY_MIPI_SENSOR_ERROR;
    }
    
    configSize = (sizeof(Cy_OV5640_Base_configuration_settings))/(sizeof(cy_stc_Ov5640_reg_t));
    return Cy_OV5640_ImageSensor_Write_ConfigurationSettings(Cy_OV5640_Base_configuration_settings, configSize);
}

/*******************************************************************************
* Function Name: Cy_OV5640_ImageSensor_Set_VGA_Config
****************************************************************************//**
*
* \brief
* Configure OV5640 for VGA@60FPS.
*
* \param none
*
* \return
* cy_en_mipi_sensor_result_t : function result type
*
*******************************************************************************/
cy_en_mipi_sensor_result_t Cy_OV5640_ImageSensor_Set_VGA_Config(void)
{
    uint16_t configSize;
    if (glIsValidSensor != true)
    {
        return CY_MIPI_SENSOR_ERROR;
    }

    configSize = (sizeof(Cy_OV5640_VGA_configuration_settings))/(sizeof(cy_stc_Ov5640_reg_t));
    return Cy_OV5640_ImageSensor_Write_ConfigurationSettings(Cy_OV5640_VGA_configuration_settings, configSize);
}

/*******************************************************************************
* Function Name: Cy_OV5640_ImageSensor_Set_720P_Config
****************************************************************************//**
*
* \brief
* Configure OV5640 for 720P@60FPS.
*
* \param none
*
* \return
* cy_en_mipi_sensor_result_t : function result type
*
*******************************************************************************/
cy_en_mipi_sensor_result_t Cy_OV5640_ImageSensor_Set_720P_Config(cy_mipisensor_stc_cfg_t * pstcCfg)
{
    uint16_t configSize;
    if (glIsValidSensor != true)
    {
        return CY_MIPI_SENSOR_ERROR;
    }

    if(pstcCfg->u16Framerate == FRAME_RATE_30)
    {
        configSize = (sizeof(Cy_OV5640_720P_30FPS_configuration_settings))/(sizeof(cy_stc_Ov5640_reg_t));
        return Cy_OV5640_ImageSensor_Write_ConfigurationSettings(Cy_OV5640_720P_30FPS_configuration_settings, configSize);
    }

    if(pstcCfg->u16Framerate == FRAME_RATE_60)
    {
        configSize = (sizeof(Cy_OV5640_720P_60FPS_configuration_settings))/(sizeof(cy_stc_Ov5640_reg_t));
        return Cy_OV5640_ImageSensor_Write_ConfigurationSettings(Cy_OV5640_720P_60FPS_configuration_settings, configSize);
    }
    return CY_MIPI_SENSOR_ERROR;
}

/*******************************************************************************
* Function Name: Cy_OV5640_ImageSensor_Set_1080P_Config
****************************************************************************//**
*
* \brief
* Configure OV5640 for 1080P@60FPS.
*
* \param none
*
* \return
* cy_en_mipi_sensor_result_t : function result type
*
*******************************************************************************/
cy_en_mipi_sensor_result_t Cy_OV5640_ImageSensor_Set_1080P_Config(cy_mipisensor_stc_cfg_t * pstcCfg)
{
    uint16_t configSize;
    if (glIsValidSensor != true)
    {
        return CY_MIPI_SENSOR_ERROR;
    }

    if(pstcCfg->u16Framerate == FRAME_RATE_15)
    {
    configSize = (sizeof(Cy_OV5640_1080P_15FPS_configuration_settings))/(sizeof(cy_stc_Ov5640_reg_t));
    return Cy_OV5640_ImageSensor_Write_ConfigurationSettings(Cy_OV5640_1080P_15FPS_configuration_settings, configSize);
    }

    if(pstcCfg->u16Framerate == FRAME_RATE_30)
    {
    configSize = (sizeof(Cy_OV5640_1080P_30FPS_configuration_settings))/(sizeof(cy_stc_Ov5640_reg_t));
    return Cy_OV5640_ImageSensor_Write_ConfigurationSettings(Cy_OV5640_1080P_30FPS_configuration_settings, configSize);
    }
    return CY_MIPI_SENSOR_ERROR;
}

/*******************************************************************************
* Function Name: Cy_OV5640_ImageSensor_Configure_Autofocus
****************************************************************************//**
*
* \brief
* Configure image sensor auto focus feature.
*
* \param none
*
* \return
* cy_en_mipi_sensor_result_t : function result type
*
*******************************************************************************/
static cy_en_mipi_sensor_result_t Cy_OV5640_ImageSensor_Configure_Autofocus(void)
{
    cy_en_mipi_sensor_result_t status = CY_MIPI_SENSOR_SUCCESS;
    uint8_t count = 0;   
    uint8_t rwBuffer = 0;
    
    if (glIsValidSensor != true)
    {
        return CY_MIPI_SENSOR_ERROR;
    }
    
    rwBuffer = 0x20;
    status = Cy_OV5640_ImageSensor_Write(CY_OV5640_SYSTEM_RESET0, 1, &rwBuffer);
    if(status != CY_MIPI_SENSOR_SUCCESS)
    {
        return status;
    }
    DELAY(CY_OV5640_CMD_IN_BW_DELAY); 
    
    for (count = 0; count <= 0x10; count++)
    {
        status = Cy_OV5640_ImageSensor_Write(cy_OV5640_auto_focus_configuration_settings[count].baseAddress, cy_OV5640_auto_focus_configuration_settings[count].numBytes, cy_OV5640_auto_focus_configuration_settings[count].buffer);
        if(status != CY_MIPI_SENSOR_SUCCESS)
        {
            return status;
        }
        DELAY(CY_OV5640_FLASH_FW_DELAY);
    }

    /* Autofocus firmware workaround */
    rwBuffer = 0x7f;
    status = Cy_OV5640_ImageSensor_Write(0x3029, 1, &rwBuffer);
    DELAY(CY_OV5640_CMD_IN_BW_DELAY);
    
    rwBuffer = 0x00;
    status = Cy_OV5640_ImageSensor_Write(CY_OV5640_SYSTEM_RESET0, 1, &rwBuffer);
    DELAY(CY_OV5640_CMD_IN_BW_DELAY);
    
    return status;
}

/*******************************************************************************
* Function Name: Cy_Mipi_Image_Sensor_Wakeup
****************************************************************************//**
*
* \brief
* Image sensor wakeup call.
*
* \param none
*
* \return
* cy_en_mipi_sensor_result_t : function result type
*
*******************************************************************************/
cy_en_mipi_sensor_result_t Cy_Mipi_Image_Sensor_Wakeup(void)
{
    cy_en_mipi_sensor_result_t status = CY_MIPI_SENSOR_SUCCESS;
    uint8_t rwBuffer = 0;    
    if (glIsValidSensor != true)
    {
        return CY_MIPI_SENSOR_ERROR;
    }

    rwBuffer = 0x21;
    status = Cy_OV5640_ImageSensor_Write(CY_OV5640_POLARITY_CTRL00, 1, &rwBuffer);
    if (status == CY_MIPI_SENSOR_SUCCESS)
    {
        rwBuffer = 0;
        status = Cy_OV5640_ImageSensor_Read(CY_OV5640_SYSTEM_CTRL0, 1, &rwBuffer);
        if (status == CY_MIPI_SENSOR_SUCCESS)
        {
            rwBuffer &= (~CY_OV5640_SYSTEM_POWER_DOWN_MASK);
            status = Cy_OV5640_ImageSensor_Write(CY_OV5640_SYSTEM_CTRL0, 1, &rwBuffer);
            DELAY(CY_OV5640_RESET_BOOT_DELAY);
        }
    }
    return status;
}

/*******************************************************************************
* Function Name: Cy_OV5640_Image_Sensor_Sleep
****************************************************************************//**
*
* \brief
* Configure defaults base setup for sensor.
*
* \param none
*
* \return
* cy_en_mipi_sensor_result_t : function result type
*
*******************************************************************************/
cy_en_mipi_sensor_result_t Cy_OV5640_Image_Sensor_Sleep(void)
{
    cy_en_mipi_sensor_result_t status = CY_MIPI_SENSOR_SUCCESS;
    uint8_t rwBuffer = 0;

    if (glIsValidSensor != true)
    {
        return CY_MIPI_SENSOR_ERROR;
    }

    status = Cy_OV5640_ImageSensor_Read(CY_OV5640_SYSTEM_CTRL0, 1, &rwBuffer);
    if (status == CY_MIPI_SENSOR_SUCCESS)
    {
        rwBuffer |= CY_OV5640_SYSTEM_POWER_DOWN_MASK;
        status = Cy_OV5640_ImageSensor_Write(CY_OV5640_SYSTEM_CTRL0, 1, &rwBuffer);
        DELAY(CY_OV5640_RESET_BOOT_DELAY);
    }
    return status;
}


/*******************************************************************************
* Function Name: Cy_Mipi_Image_Sensor_Set_ColorFormat
****************************************************************************//**
*
* \brief
* Function to set the color format and output pattern of the OV5640 chip.
*
* \param
* cy_en_mipi_sensor_format_type_t : sensor color format and sequence type
*
* \return
* cy_en_mipi_sensor_result_t : function result type
*
*******************************************************************************/
cy_en_mipi_sensor_result_t Cy_Mipi_Image_Sensor_Set_ColorFormat(cy_en_mipi_sensor_format_type_t enFmType)
{
    uint8_t rwBuffer;
    cy_en_mipi_sensor_result_t status = CY_MIPI_SENSOR_SUCCESS;

    rwBuffer = enFmType;
    status = Cy_OV5640_ImageSensor_Write(CY_OV5640_FORMAT_CONTROL, 1, &rwBuffer);
    if (status != CY_MIPI_SENSOR_SUCCESS)
    {
        return status;
    }

    return status;
}

/*******************************************************************************
* Function Name: Cy_Mipi_Image_Sensor_Set_TestPattern
****************************************************************************//**
*
* \brief
* Function to enable/disable the default test color pattern of the OV5640 chip.
*
* \param
* bool : true for enable or false for disable
*
* \return 
* cy_en_mipi_sensor_result_t : function result type
*
*******************************************************************************/
cy_en_mipi_sensor_result_t Cy_Mipi_Image_Sensor_Set_TestPattern(bool enable)
{
    uint8_t rwBuffer;
    cy_en_mipi_sensor_result_t status = CY_MIPI_SENSOR_SUCCESS;

    rwBuffer = (enable?1:0) << 7;
    status = Cy_OV5640_ImageSensor_Write(CY_OV5640_TEST_PATTERN, 1, &rwBuffer);
    if (status != CY_MIPI_SENSOR_SUCCESS)
    {
        return status;
    }

    return status;
}

/*******************************************************************************
* Function Name: Cy_Mipi_Image_Sensor_Enable_Capture
****************************************************************************//**
*
* \brief
* Enable the capture engine for MIPICSI-2 source.
*
* \param
* bool : true for enable or false for disable
*
* \return
* cy_en_mipi_sensor_result_t : function result type
*
*******************************************************************************/
cy_en_mipi_sensor_result_t Cy_Mipi_Image_Sensor_Set_MipiCapturePath(bool enable)
{
    uint8_t capCfg;
    cy_en_mipi_sensor_result_t status = CY_MIPI_SENSOR_SUCCESS;

    if (glIsValidSensor != true)
    {
        return CY_MIPI_SENSOR_ERROR;
    }
    else
    {
        capCfg = enable ? 1 : 0;
        CY_SET_REG32(CYREG_VIDEOSS0_VIDEOSSCFG_CAP0CFG, (uint32_t)capCfg);   // Set the CSI as capture source
    }

    return status;
}

/*******************************************************************************
* Function Name: Cy_Mipi_Image_Sensor_Init
****************************************************************************//**
*
* \brief
* Initializes the Image Sensor and control interface.
*
* \param none
*
* \return
* cy_en_mipi_sensor_result_t : function result type
*
* \note 
* SCB7 is used as a sensor control interface, do not change it. Should be
* called before calling any other image sensor api.
*
*******************************************************************************/
cy_en_mipi_sensor_result_t Cy_Mipi_Image_Sensor_Init(cy_mipisensor_stc_cfg_t * pstcCfg)
{
    cy_en_mipi_sensor_result_t status = CY_MIPI_SENSOR_SUCCESS;
    
    Cy_OV5640_ImageSensor_PowerEnable();
    Cy_OV5640_ImageSensor_I2C_Init();                           // Initialize I2C control path

    status = Cy_OV5640_ImageSensor_VerifyChipId();              // Verify sensor chip id
    if (status != CY_MIPI_SENSOR_SUCCESS)
    {
        return status;
    }
    
    status = Cy_OV5640_ImageSensor_Set_Base();                  // Image sensor base setup
    if (status != CY_MIPI_SENSOR_SUCCESS)
    {
        return status;
    }
        
    status = Cy_OV5640_ImageSensor_Configure_Autofocus();       // Sensor set auto focus
    if (status != CY_MIPI_SENSOR_SUCCESS)
    {
        return status;
    }
    
    if(pstcCfg->u16Resolution == RESOLUTION_640_480 )
    {
        status = Cy_OV5640_ImageSensor_Set_VGA_Config();
    }
    
    else if(pstcCfg->u16Resolution == RESOLUTION_1280_720)
    {
        status = Cy_OV5640_ImageSensor_Set_720P_Config(pstcCfg);
    }

    else if(pstcCfg->u16Resolution == RESOLUTION_1920_1080)
    {
        status = Cy_OV5640_ImageSensor_Set_1080P_Config(pstcCfg);
    }
    else
    {
        //Do Nothing
    }
    if (status != CY_MIPI_SENSOR_SUCCESS)
    {
        return status;
    }

    status = Cy_OV5640_Image_Sensor_Sleep();                    // Sensor sleep will turn off camera
    if (status != CY_MIPI_SENSOR_SUCCESS)
    {
        return status;
    }

    return status;
}

/*******************************************************************************
* Function Name: Cy_Mipi_Image_Sensor_DeInit
****************************************************************************//**
*
* \brief
* De-Initializes the Image Sensor Interface.
*
* \param none
*
* \return
* cy_en_mipi_sensor_result_t : function result type
*
*******************************************************************************/
cy_en_mipi_sensor_result_t Cy_Mipi_Image_Sensor_DeInit(void)
{
    cy_en_mipi_sensor_result_t status = CY_MIPI_SENSOR_SUCCESS;
    
    status = Cy_OV5640_Image_Sensor_Sleep();                    // Sensor sleep will turn off camera
    if (status != CY_MIPI_SENSOR_SUCCESS)
    {
        return status;
    }

    Cy_SCB_I2C_DeInit(CY_MIPI_CSI_I2C_TYPE);

    return status;
}

/******************************************************************************/
/* [] END OF FILE */
/******************************************************************************/
