/**********************************************************************************************************************
 * \file cy_ov5640.h
 * \copyright Copyright (C) Infineon Technologies AG 2025
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef CY_OV5640_CONFIG_H_
#define CY_OV5640_CONFIG_H_

#include <stddef.h>
#include <stdbool.h>


#if defined(__cplusplus)
extern "C" {
#endif

/* Structure to store the Address/Value pair for each register */
typedef struct
{
    uint16_t regAddr;
    uint8_t regValue;
} cy_stc_Ov5640_reg_t;

/* Structure to store parameters for each auto focus register */
typedef struct
{
    uint16_t baseAddress;
    uint16_t numBytes;
    uint8_t buffer[256];
} cy_stc_Ov5640_af_reg_t;

extern cy_stc_Ov5640_reg_t Cy_OV5640_Base_configuration_settings[256];
extern cy_stc_Ov5640_af_reg_t cy_OV5640_auto_focus_configuration_settings [];
extern cy_stc_Ov5640_reg_t Cy_OV5640_VGA_configuration_settings[59];
extern cy_stc_Ov5640_reg_t Cy_OV5640_720P_30FPS_configuration_settings [56];
extern cy_stc_Ov5640_reg_t Cy_OV5640_720P_60FPS_configuration_settings [61];
extern cy_stc_Ov5640_reg_t Cy_OV5640_1080P_15FPS_configuration_settings [64];
extern cy_stc_Ov5640_reg_t Cy_OV5640_1080P_30FPS_configuration_settings [63];

#if defined(__cplusplus)
}
#endif  /* __cplusplus */

#endif  /* CY_OV5640_CONFIG_H */


/* [] END OF FILE */
